document.body.addEventListener('loadContent'), loadContent(event))

function loadContent(event){
	var newContent = generateNewContent();
	return newContent
}

function generateNewContent(){
	return "<p> This is the new local content generated by the local js function!<p>"
}
